AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

## A text string that describes the template.
Description: >
  The Order service is part of the ACME Fitness Serverless Shop. The goal of this specific service is to interact with the catalog, front-end, and make calls to the order services.

## Values to pass to your template at runtime (when you create or update a stack).
Parameters:
  Version:
    Type: String
  Author:
    Type: String
  Team:
    Type: String
  Feature:
    Type: String
    Default: acmeserverless
  Stage:
    Type: String
    Default: dev

## Specifies the stack resources and their properties.
Resources:
  AddOrder:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-sqs-add
      Runtime: go1.x
      CodeUri: bin/
      FunctionName: AddOrder
      Description: A Lambda function to add orders
      MemorySize: 256
      Timeout: 10
      Tracing: Active
      Policies:
        - AWSLambdaRole
        - DynamoDBCrudPolicy:
            TableName: "Order"
        - SQSSendMessagePolicy:
            QueueName: !Sub '${Stage}-${Feature}-payment-request'
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          RESPONSEQUEUE: !Sub 'https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${Stage}-${Feature}-payment-request'
          TABLE: Order
      Events:
        AddAPI:
          Type: Api
          Properties:
            Path: /order/add/{userid}
            Method: POST
      Tags:
        version: !Ref Version
        author: !Ref Author
        team: !Ref Team
        feature: !Ref Feature
        region: !Ref AWS::Region
      VersionDescription: !Ref Version
  AddOrderLogGroup:
    Type: "AWS::Logs::LogGroup"
    DependsOn: "AddOrder"
    Properties: 
      RetentionInDays: 1
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref AddOrder]]

## Describes the values that are returned whenever you view your stack's properties.
Outputs:
  AddOrderARN:
    Description: ARN for the AddOrder function
    Value: !GetAtt AddOrder.Arn
  AddOrderURL:
    Description: "API Gateway endpoint URL to add an orders"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/order/add/{userid}"