AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

## A text string that describes the template.
Description: >
  The Order service is part of the ACME Fitness Serverless Shop. The goal of this specific service is to interact with the catalog, front-end, and make calls to the order services.

## Values to pass to your template at runtime (when you create or update a stack).
Parameters:
  Version:
    Type: String
  Author:
    Type: String
  Team:
    Type: String
  Feature:
    Type: String
    Default: acmeserverless
  Stage:
    Type: String
    Default: dev

## Specifies the stack resources and their properties.
Resources:
  AllOrders:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-all-orders
      Runtime: go1.x
      CodeUri: bin/
      FunctionName: AllOrders
      Description: A Lambda function to get all orders
      MemorySize: 256
      Timeout: 10
      Tracing: Active
      Policies:
        - AWSLambdaRole
        - DynamoDBCrudPolicy:
            TableName: "Order"
      Environment:
        Variables:
          TABLE: "Order"
      Events:
        GetAllOrdersAPI:
          Type: Api
          Properties:
            Path: /order/all
            Method: GET
      Tags:
        version: !Ref Version
        author: !Ref Author
        team: !Ref Team
        feature: !Ref Feature
        region: !Ref AWS::Region
      VersionDescription: !Ref Version
  AllOrdersLogGroup:
    Type: "AWS::Logs::LogGroup"
    DependsOn: "AllOrders"
    Properties: 
      RetentionInDays: 1
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref AllOrders]]

## Describes the values that are returned whenever you view your stack's properties.
Outputs:
  AllOrdersURL:
    Description: "API Gateway endpoint URL to get all orders"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/order/all"