AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

## A text string that describes the template.
Description: >
  The Order service is part of the ACME Fitness Serverless Shop. The goal of this specific service is to interact with the catalog, front-end, and make calls to the order services.

## Values to pass to your template at runtime (when you create or update a stack).
Parameters:
  Version:
    Type: String
  Author:
    Type: String
  Team:
    Type: String
  Feature:
    Type: String
    Default: acmeserverless
  Stage:
    Type: String
    Default: dev

## Specifies the stack resources and their properties.
Resources:
  ShipOrder:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-sqs-ship
      Runtime: go1.x
      CodeUri: bin/
      FunctionName: ShipOrder
      Description: A Lambda function to send orders to the shipment service
      MemorySize: 256
      Timeout: 10
      Tracing: Active
      Policies:
        - AWSLambdaRole
        - DynamoDBCrudPolicy:
            TableName: "Order"
        - SQSSendMessagePolicy:
            QueueName: !Sub '${Stage}-${Feature}-shipment-request'
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          TABLE: "Order"
          RESPONSEQUEUE: !Sub 'https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${Stage}-${Feature}-shipment-request'
      Events:
        SendToShipment:
          Type: SQS
          Properties:
            Queue: !Sub 'arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${Stage}-${Feature}-payment-response'
            BatchSize: 1
            Enabled: true
      Tags:
        version: !Ref Version
        author: !Ref Author
        team: !Ref Team
        feature: !Ref Feature
        region: !Ref AWS::Region
      VersionDescription: !Ref Version
  ShipOrderLogGroup:
    Type: "AWS::Logs::LogGroup"
    DependsOn: "ShipOrder"
    Properties: 
      RetentionInDays: 1
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref ShipOrder]]

## Describes the values that are returned whenever you view your stack's properties.
Outputs:
  ShipOrderARN:
    Description: ARN for the ShipOrder function
    Value: !GetAtt ShipOrder.Arn