AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

## A text string that describes the template.
Description: >
  The Order service is part of the ACME Fitness Serverless Shop. The goal of this specific service is to interact with the catalog, front-end, and make calls to the order services.

## Values to pass to your template at runtime (when you create or update a stack).
Parameters:
  Version:
    Type: String
  Author:
    Type: String
  Team:
    Type: String
  Feature:
    Type: String
    Default: acmeserverless
  Stage:
    Type: String
    Default: dev

## Specifies the stack resources and their properties.
Resources:
  UpdateOrder: 
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-sqs-update
      Runtime: go1.x
      CodeUri: bin/
      FunctionName: UpdateOrder
      Description: A Lambda function to update orders
      MemorySize: 256
      Timeout: 10
      Tracing: Active
      Policies:
        - AWSLambdaRole
        - DynamoDBCrudPolicy:
            TableName: "Order"
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          TABLE: "Order"
      Events:
        UpdateOrder:
          Type: SQS
          Properties:
            Queue: !Sub 'arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${Stage}-${Feature}-shipment-response'
            BatchSize: 1
            Enabled: true
      Tags:
        version: !Ref Version
        author: !Ref Author
        team: !Ref Team
        feature: !Ref Feature
        region: !Ref AWS::Region
      VersionDescription: !Ref Version
  UpdateOrderLogGroup:
    Type: "AWS::Logs::LogGroup"
    DependsOn: "UpdateOrder"
    Properties: 
      RetentionInDays: 1
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref UpdateOrder]]

## Describes the values that are returned whenever you view your stack's properties.
Outputs:
  UpdateOrderARN:
    Description: ARN for the UpdateOrder function
    Value: !GetAtt UpdateOrder.Arn